[package]
name = "user"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[[bin]]
name = "initproc"
path = "src/initproc/bin/main.rs"

[[bin]]
name = "sh"
path = "src/sh/bin/main.rs"

[[bin]]
name = "hello"
path = "src/hello/bin/main.rs"

[[bin]]
name = "bye"
path = "src/bye/bin/main.rs"

[[bin]]
name = "fstest"
path = "src/fstest/bin/main.rs"

[[bin]]
name = "rrtest"
path = "src/rrtest/bin/main.rs"

[[bin]]
name = "ls"
path = "src/ls/bin/main.rs"

[[bin]]
name = "cat"
path = "src/cat/bin/main.rs"

[[bin]]
name = "shutdown"
path = "src/shutdown/bin/main.rs"

[[bin]]
name = "echo"
path = "src/echo/bin/main.rs"

[[bin]]
name = "calc"
path = "src/calc/bin/main.rs"

[dependencies]
lib = { path = "../user-lib" }

[build-dependencies]
build = { path = "../user-build" }

[package.metadata]
applications = ["initproc", "sh", "hello", "bye", "fstest", "rrtest", "ls", "cat", "shutdown", "echo", "calc"]