[package]
name = "user"
version = "0.1.0"
edition = "2024"
build = "build.rs"

[[bin]]
name = "initproc"
path = "src/initproc/bin/main.rs"

[[bin]]
name = "sh"
path = "src/sh/bin/main.rs"

[[bin]]
name = "hello"
path = "src/hello/bin/main.rs"

[[bin]]
name = "bye"
path = "src/bye/bin/main.rs"

[[bin]]
name = "fstest"
path = "src/fstest/bin/main.rs"

[dependencies]
lib = { path = "../user-lib" }

[build-dependencies]
build = { path = "../user-build" }

[package.metadata]
applications = ["initproc", "sh", "hello", "bye", "fstest"]